services:
  identity-server:
    build:
      context: ./firebase-auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./firebase-auth/.env
  
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./api-server/.env